"""feat: add categoria to Registro's table

Revision ID: bad91f66e351
Revises: bc6df6a449de
Create Date: 2026-05-07 22:45:55.357131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad91f66e351'
down_revision: Union[str, Sequence[str], None] = 'bc6df6a449de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('comentario', sa.String(), nullable=True))
    op.add_column('registros', sa.Column('categoria', sa.String(), nullable=True))
    op.drop_column('registros', 'comentarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('comentarios', sa.VARCHAR(), nullable=True))
    op.drop_column('registros', 'categoria')
    op.drop_column('registros', 'comentario')
    # ### end Alembic commands ###
