"""fix bug tables sqlite

Revision ID: ee03a57b3ab8
Revises: 77ba32d16cef
Create Date: 2026-05-07 16:47:25.236580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee03a57b3ab8'
down_revision: Union[str, Sequence[str], None] = '77ba32d16cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nivel_foco', sa.Integer(), nullable=False),
    sa.Column('tempo_minutos', sa.Integer(), nullable=False),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###
